data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer.", "answer": "True"},
    {"text": "Bananas are berries, but strawberries are not.", "answer": "True"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "There are more stars in the universe than grains of sand on all the world's beaches.", "answer": "True"},
    {"text": "A day on Venus is longer than a year on Venus.", "answer": "True"},
    {"text": "Humans share 50% of their DNA with bananas.", "answer": "True"},
    {"text": "The longest time between two twins being born is 87 days.", "answer": "True"},
    {"text": "The smallest bone in the human body is in the ear.", "answer": "True"},
    {"text": "An octopus has eight legs.", "answer": "False"},
    {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "True"},
    {"text": "A single strand of spaghetti is called a 'spaghetto'.", "answer": "True"},
    {"text": "A jiffy is a proper unit of time.", "answer": "True"},
    {"text": "M&M stands for Mars and Murrie.", "answer": "True"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "The heart of a shrimp is located in its head.", "answer": "True"},
    {"text": "The human nose can remember 50,000 different scents.", "answer": "True"},
    {"text": "The longest wedding veil was the same length as 63.5 football fields.", "answer": "True"},
    {"text": "Allodoxaphobia is the fear of opinions.", "answer": "True"},
    {"text": "Snakes can help predict earthquakes.", "answer": "True"},
    {"text": "Cows have best friends and get stressed when they are separated.", "answer": "True"},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer.", "answer": "True"},
    {"text": "There is a species of spider called the Hobo Spider.", "answer": "True"},
    {"text": "Koalas sleep up to 22 hours a day.", "answer": "True"},
    {"text": "One light year is approximately 5.88 trillion miles.", "answer": "True"},
    {"text": "Walt Disney was afraid of mice.", "answer": "True"},
    {"text": "A blue whale's heart is the size of a small car.", "answer": "True"},
    {"text": "Octopuses lay 56,000 eggs at a time.", "answer": "True"},
    {"text": "Tigers have striped skin, not just striped fur.", "answer": "True"},
    {"text": "The M&M's colors are inspired by Christmas colors.", "answer": "False"},
    {"text": "A bolt of lightning contains enough energy to toast 100,000 slices of bread.", "answer": "True"},
    {"text": "Humans are the only animals that blush.", "answer": "True"},
    {"text": "There are more cells of bacteria in your body than there are human cells.", "answer": "True"},
    {"text": "A duel between three people is called a truel.", "answer": "True"},
    {"text": "Coca-Cola was originally green.", "answer": "False"},
    {"text": "Dogs' sense of smell is about 10,000 times stronger than humans'.", "answer": "True"},
    {"text": "The shortest war in history lasted 38 minutes.", "answer": "True"},
    {"text": "A sneeze travels about 100 miles per hour.", "answer": "True"},
    {"text": "A human could swim through a blue whale's veins.", "answer": "True"},
    {"text": "There are more fake flamingos in the world than real flamingos.", "answer": "True"},
    {"text": "A shrimp's heart is in its tail.", "answer": "False"},
    {"text": "A crocodile cannot stick its tongue out.", "answer": "True"},
    {"text": "A woman has walked on the moon.", "answer": "False"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "The only letter not in the periodic table is J.", "answer": "True"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "An ostrich's eye is bigger than its brain.", "answer": "True"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "Venus is the hottest planet in the solar system.", "answer": "True"},
    {"text": "Humans can distinguish between over a trillion different smells.", "answer": "True"},
    {"text": "It takes light from the Sun 8 minutes and 20 seconds to reach Earth.", "answer": "True"},
    {"text": "Some cats are allergic to humans.", "answer": "True"},
    {"text": "The smallest country in the world is Vatican City.", "answer": "True"},
    {"text": "The longest English word is 189,819 letters long.", "answer": "True"},
    {"text": "Mammoths still walked the Earth when the Great Pyramid was being built.", "answer": "True"},
    {"text": "There is no sound in space.", "answer": "True"},
    {"text": "Goldfish only have a memory of three seconds.", "answer": "False"},
    {"text": "You can't hum while holding your nose closed.", "answer": "True"},
    {"text": "Dolphins have names for each other.", "answer": "True"},
    {"text": "The inventor of the Pringles can is now buried in one.", "answer": "True"},
    {"text": "A snail can sleep for three years.", "answer": "True"},
    {"text": "A chef's hat has exactly 100 pleats.", "answer": "True"},
    {"text": "Dragonflies have a lifespan of six months.", "answer": "False"},
    {"text": "Some fungi create zombies, then control their minds.", "answer": "True"},
    {"text": "If you cut down a cactus in Arizona, you'll be penalized.", "answer": "True"},
    {"text": "Rabbits can't vomit.", "answer": "True"},
    {"text": "The longest place name in the world is 85 letters long.", "answer": "True"},
    {"text": "Koalas have fingerprints.", "answer": "True"},
    {"text": "Humans are the only animals that enjoy spicy foods.", "answer": "True"},
    {"text": "Sea otters hold hands when they sleep to keep from drifting apart.", "answer": "True"},
    {"text": "A baby octopus is about the size of a flea when it is born.", "answer": "True"},
    {"text": "Penguins can jump six feet out of water.", "answer": "True"},
    {"text": "Slugs have four noses.", "answer": "True"},
    {"text": "A cow gives nearly 200,000 glasses of milk in a lifetime.", "answer": "True"},
    {"text": "Bats are the only mammals that can fly.", "answer": "True"},
    {"text": "Elephants are the only animals that can't jump.", "answer": "False"},
    {"text": "Frogs drink water through their skin.", "answer": "True"},
    {"text": "Polar bear skin is black.", "answer": "True"},
    {"text": "Humans are born with 300 bones, but by the time they become adults, they only have 206.","answer":"True"}]
